### ISSUE TITLE
Workers get "frozen" after page times out

### ISSUE THREAD

**Issue by topherhunt** [Buzzvil/ghost-town#12]
We're using GhostTown to manage PhantomJS renders and image processing tasks that are likely to fail often on slow-loading pages etc. Recently when queuing up a large number of items I noticed that the GhostTown server eventually stops processing all jobs; the Master continues to check the queue, but the four Workers appear to have frozen or died.

Here's a highly simplistic script in which the worker never returns the job (presumably because of some slow-loading page or intricate bug):

```
var town = require("ghost-town")({ pageDeath: 1000, pageTries: 0 });

if (town.isMaster) { // MASTER: poll Redis for new jobs and queue them locally
  console.log("MASTER starting up.");

  function check_for_new_jobs(){
    console.log("MASTER queuing up job.");

    town.queue({}, function(error, data){
      if (error) {
        console.log("WORKER timed out!");
      } else {
        console.log("WORKER job complete.");
      }
    });

    setTimeout(check_for_new_jobs, 1000);
  }

  setTimeout(check_for_new_jobs, 1000);
} else { // WORKER: accept a job from the queue, process it and return the result
  console.log("WORKER starting up.");

  town.on("queue", function(page, job_data, next){
    console.log("WORKER starting job.");
    // Some failure state means that this worker never calls next()
  });
}
```

Note the `pageDeath` setting. When I run this script, I would expect the following behavior:

 - Master queues up jobs once per second
 - The worker starts a job
 - 1 second later, the job times out, and the worker starts on the next one in the queue
 - Workers continue starting jobs and timing out indefinitely

Instead, here's an output of the behavior I see:

```
MASTER starting up.
WORKER starting up.
WORKER starting up.
WORKER starting up.
WORKER starting up.
MASTER queuing up job.
WORKER starting job.
MASTER queuing up job.
WORKER starting job.
WORKER timed out!
WORKER timed out!
MASTER queuing up job.
WORKER starting job.
WORKER timed out!
MASTER queuing up job.
WORKER starting job.
WORKER timed out!
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
MASTER queuing up job.
```

As you can see, the four workers start on exactly 4 jobs. Each job times out after 1 second (as expected), but the worker never moves on to another job, it just hangs indefinitely.

The above script is obviously built to fail, but my much more complex script boils down to the same thing: when a job times out, its worker doesn't move on to the next item in the queue for some reason.

Any idea why this is happening? Any workaround you can think of? Thanks in advance!

**Comment by tkazec** [comment]
Yes! We had this too, though for us the issue wouldn't show up until the process ran for a few days. Essentially, the `pageDeath` setting only affects the master, since the worker can't exactly stop its code from running.

Setting `workerShift` should fix things. We have it configured to 1 hour, which is safe for us because it usually takes a day for any single worker to get stuck. You'll probably need to adjust it for your own needs - low enough to ensure that there will always be free workers.

**Comment by topherhunt** [comment]
Thanks @tkazek. After some experimenting we found a more-or-less workaround using `workerShift` and `workerDeath`, relying on the fact that there's not much penalty for killing and restarting a worker: each worker is killed after 1 minute but `workerDeath` is set to a low number such that under the normal workflow workers will never get killed while in the middle of a legitimate job. With this in place, the issue has disappeared and our workers' productivity isn't noticably reduced, so we're happy with that for now.

Thanks!

**Comment by tkazec** [comment]
@topherhunt Glad to hear you've fixed it. However, I would be careful with such a low `workerDeath`... Restarting every worker within 1 minute seems a bit drastic. I would suggest looking into upping `pageCount` and/or `workerCount` so that you can handle a higher number of frozen jobs at a time and therefore have to restart workers less.

**Comment by topherhunt** [comment]
Thanks @tkazec we'll take a close look at this and consider a less extreme solution. But in the meantime, happily, things are working way better than before.
