### ISSUE TITLE
Fire event when queue is left empty?

### ISSUE THREAD

**Issue by fpinzn** [Buzzvil/ghost-town#15]
I could use this feature in a project I'm working on. I can do a PR if you consider it useful.

**Comment by tkazec** [comment]
Sounds simple enough. What's your use case?

**Comment by fpinzn** [comment]
I'm fetching the urls to be used in the workers from an endpoint that gives me n at a time, and theres a quota (I can't simply make multiple requests to fetch them all a priori) So the simplest way would be to get the master notified that the queue is empty to fetch a new batch of urls.

**Comment by tkazec** [comment]
No need for an event there.. just set a counter after fetching a batch, then decrement and check it each time a task finishes.
