### ISSUE TITLE
Add onStdout and onStderr to options for phantomjs-node

### ISSUE THREAD

**Issue by katrotz** [Buzzvil/ghost-town#17]
Can the `onStdout` and `onStderr` be added to the options list passed to `phantomjs-node` so that it could be possible to catch the output send to `/dev/stdout` from a phantomJS script.

A use case would be rendering a PDF file with phantomJS to stdout, then catching the rendered output and passing it along to other components concerned about PDF content.

**Comment by tkazec** [comment]
Ghost Town supresses `phantom`'s default PhantomJS stdout and stderr logging. Listen to the `.stdout` and `.stderr` streams on the `Worker#phantom` object instead.

**Comment by katrotz** [comment]
Thanks for the quick response. Didn't spotted this in the documentation :+1:

**Comment by tkazec** [comment]
It's more of a `phantom` feature but I should probably add it to the Ghost Town docs...
