### ISSUE TITLE
Tests are failing.

### ISSUE THREAD

**Issue by codechimera** [Buzzvil/ghost-town#18]
So, I have created a small project using ghost-town, but no items that I queued were ever going to my worker, so I decided to run the project test suite to ensure everything was going as expected on my system.

However, when I run the test suite (after running `npm install --dev`), all I get is multiple instances of the error below:
````
Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at sendHelper (cluster.js:696:8)
    at send (cluster.js:683:5)
    at EventEmitter.cluster._getServer (cluster.js:552:5)
    at listen (net.js:1271:11)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
````

I am using node 4.1.0 on OSX 10.11. All dependencies installed with no errors.

**Comment by tkazec** [comment]
Ghost Town doesn't (currently) work with anything newer than Node 0.10. Haven't fixed this because we still use 0.10 at Buzzvil, but definitely need to do so in the near future.

If you could track down why, or even fix it in a pull request, that'd be super helpful! :)

**Comment by codechimera** [comment]
I'll try to take some time to look at it. 

As an aside, I was able to get it working pretty solid in node 4.1.0 and io 3.3.1 by not providing any options, so it looks like other than updating some dependencies it's nearly ready for newer versions. 

If/when I get a chance to work on the tests I may (probably will) look into updating supported versions too.

**Comment by tkazec** [comment]
Not providing options works? Odd. I think the phantom dependency is fine. Thought there's just an issue with clustering based on your error...

Thanks!

**Comment by tkazec** [comment]
Ghost Town 3 will support PhantomJS 2.1, Node 4, and version 2 of the Node Phantom package. Hopefully coming soon!

**Comment by jborden13** [comment]
@tkazec any idea on the timing of v3?  We are trying to determine whether ditching GT in favor of rolling our own is best...

**Comment by tkazec** [comment]
@jborden13 Hopefully within the next few weeks, but in the meantime feel free to try upgrading it yourself – the process should be straightforward.

1. Upgrade dependencies.
2. Update Node Phantom calls to their new format.
3. Fix the Cluster issues.
