### ISSUE TITLE
page.evaluate always undefined

### ISSUE THREAD

**Issue by jborden13** [Buzzvil/ghost-town#20]
No matter how I try it, I cannot get a page.evaluate to return me any info about the page.  I've tried setting wait timeouts and intervals and nothing gets it to work.  page.render works without issue, what am I missing from page.evaluate()?

Thank you!

`town.on("queue", function (page, data, next) {

		page.open(data.Url, function () {
			page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js", function () {
				//setTimeout(function () {
					var btnCount = page.evaluate(function () {
						return $("button").length;
					});
					console.log(btnCount);
				//}, 2000);
			});
		});
	});`

**Comment by tkazec** [comment]
We do not modify the `phantom` object at all, so it should work exactly the same with or without Ghost Town. Unfortunately this means I cannot help with issues with `phantom`. Please check their v1 documentation: https://www.npmjs.com/package/phantom
