### ISSUE TITLE
Ghost-Town on Nodejs 0.10 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by jynclr** [Buzzvil/ghost-town#21]
Would you happen to know if there is a difference between the way NodeJS works on a windows server as opposed to a linux box? In the ghost-town example, "town.on" never fires as a worker thread. 

I have written console log lines to get some information and I have found the following. In "Master.prototype._process = function ()" I noticed that "this._workerQueue.length" is always 0, and thus never falls into the while loop. What ends up happening is "town.on('queue')..." never fires. For this reason, I have not been able to get Ghost-Town to work on a Windows Server 2012 R2. I am running NodeJS v0.10.0 for Windows.

**Comment by tkazec** [comment]
If the `workerQueue` is always zero, then there is an issue with the workers launching. Can you verify that 1) `Worker` classes are created and 2) the `phantom.create` callback is fired?

**Comment by jynclr** [comment]
Apologies for taking so long to respond. I had to tend to a pressing issue. I have not yet confirmed your questions so I do not have an answer for you. We have decided to do our work in Linux instead of Windows. If we move back to a Windows platform, I will revisit this issue then. Thank you for your prompt response.
