### ISSUE TITLE
RPC GhostTown

### ISSUE THREAD

**Issue by jborden13** [Buzzvil/ghost-town#22]
Hi, I'm attempting to run GhostTown as an RPC using the Request/Reply socket types.  Everything is working great, until it is time to respond back with a message.  I've tried responding directly back to the replyTo, but I'm getting:

`Error: Channel closed by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - queue name 'amq.gen-sMgjS-5c4qvKKR2ArMhKTA' contains reserved prefix 'amq.*'`

Which makes sense that it's a reserved queue name.  But if I can't write to it, how do I reply?

**Request:**

```
context.on("ready", function () {
    var request = context.socket("REQ", {expiration: TIMEOUT}); 
     request.setEncoding('utf8');
     request.on("data", function (message) {
      process.nextTick(function () {
        request.close();
        res.send(message, {});
      });
    });
     request.connect("RPCQueueName", function () {
      var message = JSON.stringify(req.body);
      console.log(request);
      request.write(message, "utf8");
    });
  });
```

**Reply:**

```
town.on("queue", function (page, json, next) {
reply.connect(json.ReplyTo, function () {
							reply.setEncoding('utf8');
							reply.write(JSON.stringify({ Response: 'response' }), "utf8");
						});
});
```

I've tried messing with the replyTo and correlationId to no avail.  Do you know of any ways to reply directly to an AMPQ queue - or another method?

**Comment by tkazec** [comment]
Sorry, I'm not familiar with AMPQ – this seems more like an issue with that rather than Ghost Town? Don't forget you need to call `town.queue()` at some point. Let me know if you have any integration issues.

**Comment by jborden13** [comment]
Yea, sorry mate.  You're right.  My code bases were starting to blend together.
