### ISSUE TITLE
Screen Capturing

### ISSUE THREAD

**Issue by ravitheja307** [Buzzvil/ghost-town#29]
Hi

How can I capture screen using ghost-town.
I tried
`town.on('queue',function(page , data , next){
         page.open('http://google.ca')
                  .then(status => {
                               console.log(status);
                               page.render("google.png");
                 });   
});`

`

**Comment by tddyco** [comment]
Hi, please refer to the documentation at https://github.com/amir20/phantomjs-node. Ghost Town directly exposes their API via `page`.

You'll probably want to:
1. Pass the URL to screenshot via `Master#queue(data, [asap], next)`.
2. Load and render the given URL via `page` and `data`.
3. Send back the filename via `next(err, data)`.

Or you can pass back a Buffer – just refer to Ghost Town's README.md.
